In [5]:
import numpy as np

In [2]:
a=np.array([[1,8,1],[2,17,12],[3,13,30]])
print(a)

[[ 1  8  1]
 [ 2 17 12]
 [ 3 13 30]]


In [6]:
print(np.sort(a,axis=None))


[ 1  1  2  3  8 12 13 17 30]


In [7]:
print(a.ndim)
print(a.shape)
print(a.itemsize)
print(a.size)
print(a.itemsize*a.size)


2
(3, 3)
4
9
36


In [10]:
b=np.reshape(a,(9))
b

array([ 1,  8,  1,  2, 17, 12,  3, 13, 30])

In [18]:
c=np.random.randint(6, size=(2, 3))
c

array([[1, 3, 0],
       [1, 4, 5]])

In [19]:
np.transpose(c)

array([[1, 1],
       [3, 4],
       [0, 5]])